### PR TITLE
Changed so properties can be read from ember-data records

### PR DESCRIPTION
**Pull request by bentacles**
In ember-data records are accessed via the get method.
If d[property] doesn't exist then d.get(property) will be called.
Reference: Issue #34

### CODE REVIEW

**Comment by Wildhoney** [comment]
I think you're going to need to check if `get` is defined on `d` before you attempt to invoke it. Otherwise we'll run into the issues we're seeing in Travis.

`var hasGet = d.hasOwnProperty('get');`

If it doesn't have a `get` then let's return `undefined` or `null` &ndash; assumimg that the direct property validates as `isNone`.

**Comment by bentacles** [comment]
Added changes to check the hasOwnProperty and now the Travis CI build passes.

**Comment by Wildhoney** [comment]
@bentacles Perfect! Thanks :beers:

**Comment by neverfox** [comment]
@Wildhoney @bentacles So the problem I've having is that `hasOwnProperty('get')` seems to be returning `false` for Ember objects using 1.5. So even in cases where you can call `get('myProperty')` just fine, you cannot detect that fact from `hasOwnProperty('get')`. I don't know if there's another way to check but this has failed to do the right thing when my content is an ArrayProxy containing Ember.Objects (I'm using [fireplace](https://github.com/rlivsey/fireplace) ObjectCollection and Model, which extends each respectively). I'm actually surprised this isn't an issue when using ember-data because I thought they pretty much extended the same Ember classes.

**Pull request merged**
